spring:
  config:
    activate:
      on-profile: dev

  #----------------------------------------------
  #Redis
  #----------------------------------------------
  #tunel ssh para redis ssh -L 6379:10.43.198.211:6379 samuel-admin@servidor-b
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

app:
  frontend-url: https://stringtecnologiadf.org:4200
  storage:
    path: documentos

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG


