spring:
  config:
    activate:
      on-profile: dev

  #----------------------------------------------
  #Redis
  #----------------------------------------------
  cache:
    type: redis

  data:
    redis:
      host: servidor-b
      port: 6379
      password: ${REDIS_PASSWORD}

app:
  frontend-url: https://stringtecnologiadf.org:4200
  storage:
    path: documentos

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG


