server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: string-api
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://${NAME_SERVER}:${PORT}/string_api
    username: ${USUARIO}
    password: ${SENHA}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      jakarta.persistence.query.timeout: 300000
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  profiles:
    default: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.stringtecnologiadf.org/realms/stringtecnologia/protocol/openid-connect/certs

storage:
  provider: minio

minio:
  endpoint: https://minio.cluster.stringtecnologiadf.org
  bucket: string-api
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}

logging:
  level:
    root: INFO
  pattern:
    dateformat: dd/MM/yyyy HH:mm:ss.SSS

api:
  infosimples:
    api-base-url: ${URL}
    api-key: ${KEY}
    time-out: 30s

app:
  storage:
    max-size: 10MB

    allowed-types:
      - application/pdf
      - image/png
      - image/jpeg

    allowed-extensions:
      - pdf
      - png
      - jpg
      - jpeg