server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: string-api


  datasource:
    url: jdbc:postgresql://${NAME_SERVER}:${PORT}/string_api
    username: ${USUARIO}
    password: ${SENHA}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000


  jpa:
    hibernate:
      ddl-auto: none   # ou validate / update (depende do seu cenário)
    properties:
      jakarta.persistence.query.timeout: 300000
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  profiles:
    default: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.stringtecnologiadf.org/realms/stringtecnologia/protocol/openid-connect/certs

logging:
  level:
    root: INFO
  pattern:
    dateformat: dd/MM/yyyy HH:mm:ss.SSS


api:
  infosimples:
    api-base-url: ${URL}
    api-key: ${KEY}
    time-out: 30s





# =========================================================
# STORAGE
# =========================================================
app:
  storage:
    max-size: 5MB

    allowed-types:
      - application/pdf
      - image/png
      - image/jpeg

    allowed-extensions:
      - pdf
      - png
      - jpg
      - jpeg