```yaml
name: Deploy Kubernetes

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versão'
        required: true
        default: 'latest'

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      # 🔹 checkout código da aplicação
      - name: Checkout app
        uses: actions/checkout@v4

      # 🔹 Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # 🔹 variáveis
      - name: Definir variáveis
        run: |
          APP_NAME=$(basename $GITHUB_REPOSITORY)
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.event.inputs.version }}

          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # 🔹 permissão Maven Wrapper
      - name: Dar permissão ao mvnw
        run: chmod +x mvnw

      # 🔥 build JAR
      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      # 🐳 build docker
      - name: Build Docker
        run: docker build -t $IMAGE .

      # 🔐 login GHCR
      - name: Login GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
          | docker login ghcr.io \
          -u ${{ github.actor }} \
          --password-stdin

      # 📦 push imagem
      - name: Push Docker Image
        run: docker push $IMAGE

      # 🔥 checkout GitOps repo
      - name: Checkout app-cluster
        run: |
          rm -rf app-cluster

          git clone \
          https://x-access-token:${{ secrets.GH_PAT }}@github.com/samuelmelo98/app-cluster.git

      # 🚀 atualiza GitOps
      - name: Atualizar GitOps
        run: |
          set -e

          echo "🚀 Aplicação: $APP_NAME"
          echo "📦 Imagem: $IMAGE"

          cd app-cluster/k8s/overlays/prod/$APP_NAME

          # atualiza imagem no kustomize
          kustomize edit set image IMAGE_PLACEHOLDER=$IMAGE

          # git config
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          # commit
          git add .

          git commit -m "deploy ${APP_NAME}:${{ github.event.inputs.version }}" \
          || echo "Sem alterações"

          # garante remote autenticado
          git remote set-url origin \
          https://x-access-token:${{ secrets.GH_PAT }}@github.com/samuelmelo98/app-cluster.git

          # push
          git push

      # ✅ fim
      - name: Finalizado
        run: |
          echo "✅ GitOps atualizado."
          echo "🤖 ArgoCD fará o deploy automaticamente."
```
